// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEIj2ZN11Nu9SMwUaic9KF3MgJRHAZdPo',
    appId: '1:232013859876:web:8b6055f889be19a4cb9cb1',
    messagingSenderId: '232013859876',
    projectId: 'ditonton-b541f',
    authDomain: 'ditonton-b541f.firebaseapp.com',
    storageBucket: 'ditonton-b541f.firebasestorage.app',
    measurementId: 'G-6HTY7R1FFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4sieIkB9-VRcaWNzsGyZoghJ8e0UypA',
    appId: '1:232013859876:android:318487d57f9efdf1cb9cb1',
    messagingSenderId: '232013859876',
    projectId: 'ditonton-b541f',
    storageBucket: 'ditonton-b541f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9iHZqHzzm5PE0R2yD5su6G6CbmT8VHK0',
    appId: '1:232013859876:ios:2b7da4312937d55ccb9cb1',
    messagingSenderId: '232013859876',
    projectId: 'ditonton-b541f',
    storageBucket: 'ditonton-b541f.firebasestorage.app',
    iosBundleId: 'com.fyyy.ditonton',
  );
}
